//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWantWant
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberAccount()
        {
            this.MemberStatusList = new HashSet<MemberStatusList>();
            this.ServiceContact = new HashSet<ServiceContact>();
        }
    
        public int AccountID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool AccountStatus { get; set; }
        public int MemberTotalPoint { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string IDCardNo { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> BitrhDay { get; set; }
        public string PhoneNo { get; set; }
        public byte[] MemberPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberStatusList> MemberStatusList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceContact> ServiceContact { get; set; }
    }
}
