//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWantWant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewIspanProjectEntities : DbContext
    {
        public NewIspanProjectEntities()
            : base("name=NewIspanProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MemberAccount> MemberAccount { get; set; }
        public virtual DbSet<MemberStatusList> MemberStatusList { get; set; }
        public virtual DbSet<ServiceContact> ServiceContact { get; set; }
        public virtual DbSet<StatusChangeReasonList> StatusChangeReasonList { get; set; }
    }
}
